### ISSUE TITLE
leakedzone.com 사이트 스크립트 추가 가능한가요??

### ISSUE THREAD

**Issue by suzukioha** [rickmiron/variado#10]
https://github.com/KurtBestor/Hitomi-Downloader/tree/master/src/extractor 이곳에서 op.gg 스크립트를 참고하여 해보니까

        image_element_list = soup.find("div", class_="<div class="item col-lg-3 col-md-3 col-sm-6 col-6">").findAll(["img", "video"])
으로 하니까  다운은 되긴 하지만 item col-lg-3 col-md-3 col-sm-6 col-6이게썸네일이라 그런가 저화질의 이미지가 받아집니다.
movie-item이 고화질이지만 item col-lg-3 col-md-3 col-sm-6 col-6" 대신에 movie-item을 넣으면 다운이 안됩니다.

https://leakedzone.com/
이 사이트의 이미지와 비디오를 다운 받고 싶지만 여러 스크립트를 참고해서 해봐도 안 되네요 ㅠㅠ

혹시 해당 사이트 추가가능할까요??

**Comment by rickmiron** [comment]
plugin:
https://github.com/rickmiron/variado/blob/main/leakedzone_downloader.py

**Comment by suzukioha** [comment]
> plugin: https://github.com/rickmiron/variado/blob/main/leakedzone_downloader.py

감사합니다! 정상 작동 합니다!
