### ISSUE TITLE
leakedzone 사이트에서 동영상파일명이 2로시작하는 파일명들은 오류가 발생합니다.

### ISSUE THREAD

**Issue by suzukioha** [rickmiron/variado#13]
다운은 되지만 동영상파일이 깨져있습니다. 
공통점은 동영상파일명이 2로시작하는 것들이었습니다.
https://leakedzone.com/hongkongdoll/video/2523022
hongkongdoll 유저를 받는다치면 다른 건 다 정상적이었는데 숫자 2로 시작하는 동영상파일들은 다 깨져있었습니다.
웹사이트에서는 다 정상적으로 재생이 되는 건 확인했습니다
다른 유저들도 마찬가지로 파일명이 2로 시작하는 것들은 동영상파일이 깨져있었습니다.
https://leakedzone.com/anaimiya/video 에서
https://leakedzone.com/anaimiya/video/2485127
https://leakedzone.com/anaimiya/video/2485119 외에도 2로 시작하는 것들은 파일이 깨져서 받아집니다 
웹사이트에서는 정상적으로 받아집니다
스크립트를 어떻게 수정해야할까요?

**Comment by rickmiron** [comment]
내가 고쳤어

**Comment by suzukioha** [comment]
> 내가 고쳤어

감사합니다 잘 됩니다!
