### ISSUE TITLE
안녕하세요 https://njav.tv/ 사이트를 추가할 수 있을까요??

### ISSUE THREAD

**Issue by ghkdqofjr1122** [rickmiron/variado#29]
안녕하세요 스크립트를 추가해주셔서 언제나 감사드립니다.

다름이 아니라 https://njav.tv/    이 사이트도 추가가 가능할까요?? 
다른 일본 AV 스트리밍 사이트에는 없는 자료들도 많아서 좋고 
사이트 속도도 빨라서 쾌적합니다.

**Comment by rickmiron** [comment]
plugin:
https://github.com/rickmiron/variado/blob/main/njavtv_downloader.py

**Comment by ghkdqofjr1122** [comment]
> plugin: https://github.com/rickmiron/variado/blob/main/njavtv_downloader.py

답변을 늦게 확인하여 죄송합니다.
제작해주셔서 감사합니다!! 
6월달에 테스트 해볼게요!!
