### ISSUE TITLE
Title containing special characters

### ISSUE THREAD

**Issue by ok9009le** [rickmiron/variado#38]
What's the best way to deal with file name compile error due to titles containing special characters [*, ', ", etc]

[Messages]
Get ofuscado
https://surrit.com/d6d58061-3cd1-459d-8b52-fd9f1c6a5aa2/1280x720/video.m3u8
https://fivetiu.com/ipx-980-uncensored-leak/cover-n.jpg
Get ofuscado
https://surrit.com/d6d58061-3cd1-459d-8b52-fd9f1c6a5aa2/1280x720/video.m3u8
https://fivetiu.com/ipx-980-uncensored-leak/cover-n.jpg
[Errno 2] No such file or directory: "hitomi_downloaded_missav\\IPX-980-UNCENSORED-LEAK * This is a example title containing special ' characters .mp4.webp"
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "dynamic_module_0", line 139, in read
 File "dynamic_module_0", line 44, in __init__
 File "dynamic_module_0", line 62, in tojpg
FileNotFoundError: [Errno 2] No such file or directory: "hitomi_downloaded_missav\\IPX-980-UNCENSORED-LEAK * This is a example title containing special ' characters .mp4.webp"

Invalid: fail=True
EOT: https://missav.com/dm76/en/ipx-980-uncensored-leak  (4.0s)

**Comment by rickmiron** [comment]
I updated the plugin, try again

**Comment by ok9009le** [comment]
Works like a charm. Thank you!
