### ISSUE TITLE
어떤 "python Downloader" 를 사용하고 있나요?

### ISSUE THREAD

**Issue by snwefly** [rickmiron/variado#4]
이 오류가 발생합니다
![image](https://github.com/rickmiron/variado/assets/88805679/2f71e780-a822-4d91-8483-f7a2e2cfd2fe)

**Comment by rickmiron** [comment]
이 프로그램의 맞춤 모듈입니다.
https://github.com/KurtBestor/Hitomi-Downloader

**Comment by snwefly** [comment]
감사합니다 😊
