### ISSUE TITLE
I have learned the basics of Python, but I found it impossible to download from civitai.com.

### ISSUE THREAD

**Issue by Summertoohot** [rickmiron/variado#63]
I have learned the basics of Python syntax and the fundamentals of web crawling, but I find it impossible to achieve what I want.

Hello, I have been studying the basic syntax of Python and learning the fundamentals of web crawling from HTML elements, but it is quite challenging, and I don’t know how to proceed. In fact, I tried analyzing the scripts by pressing F12 on the websites included in the script, but writing the script is very difficult for me.

I would like to download materials such as models and LoRA provided by Civitai, along with the HTML text descriptions and details (HTML = data-accordion), sample images, and the Generation data and Resources used information found in those sample images. Additionally, I want to extract the prompts, negative prompts, and other metadata into a TXT file. However, while I was able to tackle the image files from simpler sites, I find this task extremely challenging.

What makes it even more difficult is that there are two types of URL structures. The URL that appears when you click on the content is https://civitai.com/models/456882/styles-or-pony-and-animagine (model URL ID = 456882).

When you click on the version, the URL changes to https://civitai.com/models/456882?modelVersionId=1002962 (version URL ID = 1002962).

I would like to save the information labeled as "text" from the images into a text file. I want the model's URL ID to serve as the parent folder, and the version URL ID as the subfolder. This organization is necessary because a single model can have multiple versions.

For the given URL, the parent folder should be named with the model URL ID, which is 456882, and the subfolder should be named with the version URL ID, which is 1002962. I want the materials to be saved under the version URL ID subfolder.

I need your help. If you have time someday, could you create it for me?

Sometimes, there are multiple downloadable resources available at links like this: https://civitai.com/models/432394?modelVersionId=491214. In such cases, I would like to download all of them. There are file extensions like .safetensor or .pickletensor, but I want to download everything regardless of the extension

"There is indeed a script available for downloading resources at this GitHub repository:

CivitAI Model Grabber: https://github.com/Confuzu/CivitAI-Model-grabber?tab=readme-ov-file

civitAI_Model_downloader.py: https://github.com/Confuzu/CivitAI-Model-grabber/blob/main/civitAI_Model_downloader.py

fetch_all_models.py: https://github.com/Confuzu/CivitAI-Model-grabber/blob/main/fetch_all_models.py

However, it seems to be based on the API. I wanted to use Hitomi Downloader, but it wasn't possible.

The prompts and generation data—Resources used information and other metadata—are not downloaded, which does not satisfy my needs regarding that script.

Moreover, it was not possible to use Hitomi Downloader.

If possible, could you create a script compatible with civitai.com?"

![1](https://github.com/user-attachments/assets/e336320d-509e-4aa5-ad48-740e5c14c6af)

![2](https://github.com/user-attachments/assets/a138663b-fb15-46c1-b81d-dd83de4a9563)

![3](https://github.com/user-attachments/assets/b1c3d7b6-52d2-44fd-8362-43c6fb41abc9)

**Comment by Summertoohot** [comment]
The lectures I watched are URL 
https://www.youtube.com/watch?v=kWiCuklohdY&list=PLMsa_0kAjjrd8hYYCwbAuDsXZmHpqHvlV&index=2
https://www.youtube.com/watch?v=yQ20jZwDjTE&list=PLMsa_0kAjjrd8hYYCwbAuDsXZmHpqHvlV&index=6

Since I don't know when you will see this message, I will continue my studies. I plan to visit the existing completed scripts and the corresponding websites to compare and analyze the HTML elements

**Comment by Summertoohot** [comment]
I realized I was rushing things. I'll study again from scratch.

Even though I can't use it in Hitomi Downloader, I'll try creating my own web scraping code in Python.

I'll give it another month of effort, and if I still can't make it work, I'll post for help again.

I'll set aside my impatience and proceed slowly.

I'll start by practicing how to identify specific attributes and classes in HTML, studying existing scripts and analyzing websites along the way.

**Comment by Summertoohot** [comment]
I realized I was rushing things. I'll study again from scratch.

Even though I can't use it in Hitomi Downloader, I'll try creating my own web scraping code in Python.

I'll give it another month of effort, and if I still can't make it work, I'll post for help again.
(I apologize if I'm interrupting you while you're busy.)"

I'll set aside my impatience and proceed slowly.

I'll start by practicing how to identify specific elements and attributes in HTML, studying existing scripts and analyzing websites along the way.

I'll analyze not only the wiki scripts you've shown me but also the scripts posted by the Hitomi Downloader developer, along with the F12 Developer Tools on websites.

**Comment by rickmiron** [comment]
Well, seeing it, it's not complicated to put together the script, you need to know Python and HTML. I'll help you create the script.

**Comment by rickmiron** [comment]
Try the plugin https://github.com/rickmiron/variado/blob/main/civiai.py

**Comment by Summertoohot** [comment]
> Try the plugin https://github.com/rickmiron/variado/blob/main/civiai.py

I apologize for the late response. First of all, thank you very much!
Thank you so much for creating this!

However, I’ve encountered two issues. Could you help me resolve them?

When a model has only one version, the default URL looks like this:
https://civitai.com/models/574911/webtoon-character-cha-mia-secret-class
But the script you provided doesn’t support this type of URL. It only works for URLs like:
https://civitai.com/models/264290?modelVersionId=874078, which appear when a version is clicked.

Is it possible to adjust the script to support these default URLs? I would like it to work even if a model has only one version or if the default URL is displayed first.

The following message is an error that occurs when I use the default URL:



[Messages]
can only concatenate str (not "NoneType") to str
stop
Traceback (most recent call last):
 File "utils", line 1398, in start
 File "utils", line 1488, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 45, in geto
TypeError: can only concatenate str (not "NoneType") to str

Invalid: fail=True
EOT: https://civitai.com/models/574911/webtoon-character-cha-mia-secret-class  (1.7s)




Additionally, would it be possible to save the prompt information from the sample images as text files? I’d like to generate a text file with the same name as each sample image file, containing its prompt information. As a beginner in Stable Diffusion, I find prompt information to be very valuable.

Thank you once again. Your kindness feels like a ray of light during a tough time.

Sincerely, thank you.






![5](https://github.com/user-attachments/assets/743e1014-f7e4-4d69-8f4f-a2b7fee912d6)
![6](https://github.com/user-attachments/assets/4607a2a1-f5c3-4cbb-b036-052c16755595)
![123](https://github.com/user-attachments/assets/f7dfd8ad-12de-452b-b52c-74481d124c3a)
![1234](https://github.com/user-attachments/assets/40b2980e-9f1c-4ec1-a07f-1fc9e8e8782f)

**Comment by Summertoohot** [comment]
tI've been going through a difficult time recently due to several unfortunate events, but your kindness has truly lifted my spirits. Thank you for your help.

**Comment by rickmiron** [comment]
have you loaded the cookies?
I tried it and there were no problems
![zzzzzzzzz](https://github.com/user-attachments/assets/1c6fd56b-9438-431c-934c-01af5f97732f)

**Comment by rickmiron** [comment]
And about the extra data in the example you show, compare the sha256 hashes of the files and they are the same, which indicates that they are the same file.

**Comment by Summertoohot** [comment]
추가로 
https://civitai.com/models/58390/detail-tweaker-lora-lora
이 링크도 되지 않습니다


Invalid: [civitai] https://civitai.com/models/58390/detail-tweaker-lora-lora

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10
order / group / uid: 1 / False / 42ed0739775b40b0899f11b9f6e4c294
input: https://civitai.com/models/58390/detail-tweaker-lora-lora
type: civitai
single: False
url: https://civitai.com/models/58390/detail-tweaker-lora-lora
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1730973260.283753 (24-11-07 09:54:20 UTC) - 2s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 480
goodbyedpi: False
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
There are multiple cookies with name, '__Secure-civitai-token'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 28, in geto
 File "requests\cookies", line 202, in get
 File "requests\cookies", line 405, in _find_no_duplicates
requests.cookies.CookieConflictError: There are multiple cookies with name, '__Secure-civitai-token'

Invalid: fail=True
EOT: https://civitai.com/models/58390/detail-tweaker-lora-lora  (0.1s)

There are multiple cookies with name, '__Secure-civitai-token'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 28, in geto
 File "requests\cookies", line 202, in get
 File "requests\cookies", line 405, in _find_no_duplicates
requests.cookies.CookieConflictError: There are multiple cookies with name, '__Secure-civitai-token'

Invalid: fail=True
EOT: https://civitai.com/models/58390/detail-tweaker-lora-lora  (0.1s)

원인이 어떤 것인지 모르겠습니다.. 

확인해보니까 default url에서도 안 되는 자료들은
https://civitai.com/models/58390?modelVersionId=62833
버전을 클릭했을 시 나오는 version url 로 링크를 복사붙여넣기해도 안 된다는 것을 알았습니다.

**Comment by Summertoohot** [comment]
쿠키도 적용했으며 혹시 몰라서 vpn도 켜서 해보고, 꺼서 해보고 dpi 우회도 켰다 꺼도 똑같이 안됐습니다.
유일하게 되는 것은 
version: 4.1+ (24-07-14 10:32:29 UTC)  버전에서의
https://civitai.com/models/264290/styles-for-pony-diffusion-v6-xl-not-artists-styles
OR
https://civitai.com/models/264290?modelVersionId=874078
이 링크들만 가능했습니다.
다른 모델들의 URL들은 오류가 발생합니다. 

혹시 몰라서 civitai의 다른 계정의 쿠키도 적용해보았으나 똑같이 안 됐습니다.

**Comment by Summertoohot** [comment]
I have applied the cookies and also tried turning the VPN on and off  but the issue remains the same. The only links that work are the following ones from version: 4.1+ (24-07-14 10:32:29 UTC):

https://civitai.com/models/264290/styles-for-pony-diffusion-v6-xl-not-artists-styles
OR
https://civitai.com/models/264290?modelVersionId=874078

Only these URLs are functional. Other model URLs result in errors.

Just in case, I also applied cookies from a different Civitai account, but the issue persists. I even moved the downloader program to a different drive and ran it again, but the same error occurred.

**Comment by Summertoohot** [comment]
In the "version: 4.1+ (24-07-14 10:32:29 UTC)" version of Hitomi Downloader, the following model URLs work:

https://civitai.com/models/264290/styles-for-pony-diffusion-v6-xl-not-artists-styles
OR https://civitai.com/models/264290?modelVersionId=874078
However, other URLs all give errors.

Even after moving the Hitomi Downloader program to another drive, the same errors occur.

For example, the URL https://civitai.com/models/456882/styles-or-pony-and-animagine results in the following error message:

version: 4.1+ (24-07-14 10:32:29 UTC)
platform / locale: Windows-10 
order / group / uid: 1 / False / 798795c143354a74bd7806ff994c4e58
input: https://civitai.com/models/456882/styles-or-pony-and-animagine
type: civitai
single: False
url: https://civitai.com/models/456882/styles-or-pony-and-animagine
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1730979022.718826 (24-11-07 11:30:22 UTC) - 35s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 480
goodbyedpi: False
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
can only concatenate str (not "NoneType") to str
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 45, in geto
TypeError: can only concatenate str (not "NoneType") to str

Invalid: fail=True
EOT: https://civitai.com/models/456882/styles-or-pony-and-animagine  (2.1s)



///////////////

and the URL https://civitai.com/models/58390/detail-tweaker-lora-lora also results in an error:


Invalid: [civitai] https://civitai.com/models/58390/detail-tweaker-lora-lora

version: 4.1+ (24-07-14 10:32:29 UTC)
platform / locale: Windows-10
order / group / uid: 0 / False / 784e577ddc1e40ebb0c3d6172c4d8172
input: https://civitai.com/models/58390/detail-tweaker-lora-lora
type: civitai
single: False
url: https://civitai.com/models/58390/detail-tweaker-lora-lora
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1730979127.9481764 (24-11-07 11:32:07 UTC) - 2s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 480
goodbyedpi: False
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'result'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 42, in geto
KeyError: 'result'

Invalid: fail=True
EOT: https://civitai.com/models/58390/detail-tweaker-lora-lora  (1.7s)

'result'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 42, in geto
KeyError: 'result'

Invalid: fail=True
EOT: https://civitai.com/models/58390/detail-tweaker-lora-lora  (1.4s)


///////////////


Even the URL https://civitai.com/models/574911/webtoon-character-cha-mia-secret-class shows this error message:



Invalid: [civitai] https://civitai.com/models/574911/webtoon-character-cha-mia-secret-class

version: 4.1+ (24-07-14 10:32:29 UTC)
platform / locale: Windows-10
order / group / uid: 0 / False / 71445c652cbc4b858a973f15068a3ed6
input: https://civitai.com/models/574911/webtoon-character-cha-mia-secret-class
type: civitai
single: False
url: https://civitai.com/models/574911/webtoon-character-cha-mia-secret-class
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1730979174.1253998 (24-11-07 11:32:54 UTC) - 25s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 480
goodbyedpi: False
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
can only concatenate str (not "NoneType") to str
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 45, in geto
TypeError: can only concatenate str (not "NoneType") to str

Invalid: fail=True
EOT: https://civitai.com/models/574911/webtoon-character-cha-mia-secret-class  (1.6s)


I tried applying cookies from another Civitai account, but the issue remains.

I'm sorry, but I cannot figure out the cause of the issue.

I will test with previous versions of the downloader to see if that works.

**Comment by Summertoohot** [comment]
![777](https://github.com/user-attachments/assets/64938dae-ca57-4c87-b3d5-a1091700418c)

I copied random links based on the "highest" sorting criteria. However,
the URLs for other models cannot be downloaded like this.




https://civitai.com/models/4451/abyssorangemix2-hardcore
https://civitai.com/models/456882/styles-or-pony-and-animagine
https://civitai.com/models/7808/easynegative
https://civitai.com/models/7808?modelVersionId=9536
https://civitai.com/models/58390/detail-tweaker-lora-lora
.
.

**Comment by rickmiron** [comment]
I already updated it, try it

**Comment by Summertoohot** [comment]
> I already updated it, try it

Thank you for the feedback.
but I’m sorry. It doesn’t work for me.
It still doesn’t seem to download correctly. Also, for this link: https://civitai.com/models/264290?modelVersionId=874078 
only the "content" text file is downloaded, but not the model or LORA. I also tried applying cookies.

Other URLs are still not working either
https://civitai.com/models/4451/abyssorangemix2-hardcore
https://civitai.com/models/456882/styles-or-pony-and-animagine
https://civitai.com/models/456882?modelVersionId=1001310
https://civitai.com/models/7808/easynegative
https://civitai.com/models/7808?modelVersionId=9536
https://civitai.com/models/58390/detail-tweaker-lora-lora

The error message occurs as follows

[Messages]
'NoneType' object has no attribute 'replace'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 48, in model
AttributeError: 'NoneType' object has no attribute 'replace'

Invalid: fail=True
EOT: https://civitai.com/models/58390/detail-tweaker-lora-lora  (1.8s)

'NoneType' object has no attribute 'replace'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 48, in model
AttributeError: 'NoneType' object has no attribute 'replace'

Invalid: fail=True
EOT: https://civitai.com/models/58390/detail-tweaker-lora-lora  (1.4s)

 

'NoneType' object has no attribute 'replace'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 48, in model
AttributeError: 'NoneType' object has no attribute 'replace'

Invalid: fail=True
EOT: https://civitai.com/models/58390/detail-tweaker-lora-lora  (1.3s)


///////

 
[Messages]
'NoneType' object has no attribute 'replace'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 48, in model
AttributeError: 'NoneType' object has no attribute 'replace'

Invalid: fail=True
EOT: https://civitai.com/models/456882/styles-or-pony-and-animagine  (2.2s)

**Comment by Summertoohot** [comment]
If I input a user link, the images uploaded by the user download successfully.
However, the model-related files do not download.
If I enter this link, the 419 image files download successfully.

**Comment by rickmiron** [comment]
I already fixed it

**Comment by Summertoohot** [comment]
> I already fixed it

Thank you so much! Most pages on civitai.com are now downloadable!

However, there is one issue that may not be solvable. In cases like this link (https://civitai.com/models/6424/chilloutmix), where there is no uploader information, the download fails. It might be due to the absence of the uploader, but I’m not sure. There are some resources on civitai.com that do not have uploader information.

The error appears as follows:


Invalid: [civitai] https://civitai.com/models/6424/chilloutmix

version: 4.2+ (24-11-02 04:46:37 UTC)
platform / locale: Windows-10
order / group / uid: 0 / False / 8f4978f38a634c70a41f35f92d2323c4
input: https://civitai.com/models/6424/chilloutmix
type: civitai
single: False
url: https://civitai.com/models/6424/chilloutmix
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1731082196.0592046 (24-11-08 16:09:56 UTC) - 430s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 480
goodbyedpi: False
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'result'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 45, in model
KeyError: 'result'

Invalid: fail=True
EOT: https://civitai.com/models/6424/chilloutmix  (2.2s)

'result'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 45, in model
KeyError: 'result'

Invalid: fail=True
EOT: https://civitai.com/models/6424/chilloutmix  (2.8s)

'result'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 45, in model
KeyError: 'result'

Invalid: fail=True
EOT: https://civitai.com/models/6424/chilloutmix  (7.6s)



Thank you for listening to my feedback and creating the script. Your kindness has made my situation better. You are my silver lining. Downloading the materials was very difficult for me. I sincerely thank you for helping me

**Comment by Summertoohot** [comment]
After looking at the script you created, I realized that learning Python through basic tutorials on YouTube is not enough for me to do this. It's not something that can be done in a short period of time.

The web scraping I know how to do is limited to using Google Chrome, pressing F12, and extracting simple information like classes and attributes from the elements.
 I sincerely thank you for your help.

**Comment by rickmiron** [comment]
> After looking at the script you created, I realized that learning Python through basic tutorials on YouTube is not enough for me to do this. It's not something that can be done in a short period of time.
> 
> The web scraping I know how to do is limited to using Google Chrome, pressing F12, and extracting simple information like classes and attributes from the elements. I sincerely thank you for your help.

I do the same thing. I also look at the HTML file in view page source and check if the tags exist or are created when the web page loads, and I also analyze the files that appear in the network tab.

I already fixed it.

**Comment by Summertoohot** [comment]
> > After looking at the script you created, I realized that learning Python through basic tutorials on YouTube is not enough for me to do this. It's not something that can be done in a short period of time.
> > The web scraping I know how to do is limited to using Google Chrome, pressing F12, and extracting simple information like classes and attributes from the elements. I sincerely thank you for your help.
> 
> I do the same thing. I also look at the HTML file in view page source and check if the tags exist or are created when the web page loads, and I also analyze the files that appear in the network tab.
> 
> I already fixed it.


I sincerely thank you for taking your precious time to listen to my feedback. The kindness you have shown me will remain in my memory forever. I wish you only the best and hope that good things always come your way.

In two to three years, if my situation becomes stable, I plan to learn how to properly create Python scripts. Your kindness has truly moved me. Once again, thank you so much.

**Comment by Summertoohot** [comment]
> > After looking at the script you created, I realized that learning Python through basic tutorials on YouTube is not enough for me to do this. It's not something that can be done in a short period of time.
> > The web scraping I know how to do is limited to using Google Chrome, pressing F12, and extracting simple information like classes and attributes from the elements. I sincerely thank you for your help.
> 
> I do the same thing. I also look at the HTML file in view page source and check if the tags exist or are created when the web page loads, and I also analyze the files that appear in the network tab.
> 
> I already fixed it.


Thank you so much; most things are working well, and I really appreciate it.

However, I have encountered a case in which downloads fail
If there is no text information in the content, the download doesn't work.

Here is the link :
https://civitai.com/models/6146/arknights-gladiia

The error message appears as follows:

version: 4.2+ (24-11-02 04:46:37 UTC)
platform / locale: Windows-10
order / group / uid: 8 / False / 0b43084d256f4e6292bedae729f03759
input: https://civitai.com/models/6146/arknights-gladiia
type: civitai
single: False
url: https://civitai.com/models/6146/arknights-gladiia
dir: 
zip: 
artist: None
valid / done: True / False
range / range_p: None / None
time: 1731177761.5845404 (24-11-09 18:42:41 UTC) - 31s elapsed
tags: ['red']
lock: False
color: wait
paused: False
format: None
p2f: None
segment: None
admin: True
res: 480
goodbyedpi: False
ytdl: yt_dlp 2024.10.22
pinned: True
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 33, in model
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://civitai.com/models/6146/arknights-gladiia  (1.4s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 33, in model
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://civitai.com/models/6146/arknights-gladiia  (1.1s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 23, in read
 File "Civitai", line 33, in model
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://civitai.com/models/6146/arknights-gladiia  (1.1s)


Thank you for reviewing my feedback
